aistores/urls.py
from django.contrib import admin
from django.urls import path, include
from stocks import views
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^stocks/',include('stocks.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    path('list_items/', views.list_items, name='list_items'),
    path('add_items/', views.add_items, name='add_items'),
    path('update_items/<str:pk>/', views.update_items, name="update_items"),
    path('delete_items/<str:pk>/', views.delete_items, name="delete_items"),
    path('stock_detail/<str:pk>/', views.stock_detail, name="stock_detail"),
    path('issue_items/<str:pk>/', views.issue_items, name="issue_items"),
    path('issue_items2/<str:pk>/', views.issue_items2, name="issue_items2"),
    path('receive_items/<str:pk>/', views.receive_items, name="receive_items"),
    # path('accounts/', include('registration.backends.default.urls')),
    # path('register/', views.register, name='register'),
    path('', views.home, name='home'),
]

stocks/urls.py
# dappx/urls.py
from django.conf.urls import url
from stocks import views
# SET THE NAMESPACE!
app_name = 'stocks'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^user_login/$',views.user_login,name='user_login'),
]

stocks/models.py
from django.db import models
from django.contrib.auth.models import User

category_choice = (
		('Asset', 'Asset'),
		('Consumables', 'Consumables'),
	)

units_choice = (
			('Kgs', 'Kgs'),
			('gms', 'Gms'),
			('Nos', 'Nos'),
			('Ltrs', 'Ltrs'),
			('Mtrs', 'Mtrs')
	)

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
	  return self.user.username

class SubCategory(models.Model):
	name = models.CharField(max_length=50, blank=False, null=False)
	def __str__(self):
		return self.name


class Stock(models.Model):
	category = models.CharField(max_length=15,blank=False,null=False,
					choices=category_choice)
	subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
	part_no = models.CharField(max_length=15, blank=False, null=False, unique=True)
	item_no = models.CharField(max_length=25, blank=True, null=True)
	HSN_code = models.CharField(max_length=10, blank=True, null=True)
	item_name = models.CharField(max_length=50, blank=True, null=True)
	manufacturer = models.CharField(max_length=50, blank=True, null=True)
	quantity = models.IntegerField(default='0', blank=True, null=True)
	units = models.CharField(max_length=5,blank=False,null=False,
					choices=units_choice)
	rate = models.DecimalField(decimal_places=2,max_digits=12,default=0)
	receive_quantity = models.IntegerField(default='0', blank=True, null=True)
	receive_rate = models.DecimalField(decimal_places=2,max_digits=12,default=0)
	receive_by = models.CharField(max_length=50, blank=True, null=True)
	issue_quantity = models.IntegerField(default='0', blank=True, null=True)
	issue_by = models.CharField(max_length=50, blank=True, null=True)
	issue_to = models.CharField(max_length=50, blank=True, null=True)
	created_by = models.CharField(max_length=50, blank=True, null=True)
	reorder_level = models.IntegerField(default='0', blank=True, null=True)
	last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_by = models.CharField(max_length=50, blank=False, null=False)

	def __str__(self):
		return self.item_name

class Issues(models.Model):
	stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
	issue_quantity = models.DecimalField(default='0', max_digits=10, decimal_places=2, blank=True, null=True)
	units = models.CharField(max_length=5,blank=False,null=False,
					choices=units_choice)
	issue_to = models.CharField(max_length=10, blank=True, null=True)
	last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_by = models.CharField(max_length=50, blank=False, null=False)

	def __str__(self):
		return self.stock.item_name

stocks/forms.py
from django import forms
from .models import Stock, Issues
from stocks.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')


class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')


class StockCreateForm(forms.ModelForm):
  class Meta:
    model = Stock
    fields = ['category', 'subcategory', 'part_no', 'item_no',
    'item_name', 'manufacturer', 'quantity','units', 'rate', 'reorder_level' ]
    # labels = {  'category': ('Category of the item'),}
    widgets = {'part_no': forms.TextInput(attrs={'data-mask':"000-00-00000-00"})}

  def clean_category(self):
    category = self.cleaned_data.get('category')
    if not category:
      raise forms.ValidationError('This field is required')
    return category

  def clean_sub_category(self):
    subcategory = self.cleaned_data.get('subcategory')
    if not subcategory:
      raise forms.ValidationError('This field is required')
    return subcategory

  def clean_part_no(self):
    part_no = self.cleaned_data.get('part_no')
    if not part_no:
      raise forms.ValidationError('This field is required')

    stocks = Stock.objects.all()
    for instance in stocks:
      if instance.part_no == part_no:
        raise forms.ValidationError(part_no + " exists")
    return part_no

  def clean_item_no(self):
    item_no = self.cleaned_data.get('item_no')

    return item_no

  # def clean_HSN_code(self):
  #   HSN_code = self.cleaned_data.get('HSN_code')
  #   if not HSN_code:
  #     raise forms.ValidationError('This field is required')
  #   return HSN_code

  def clean_units(self):
    units = self.cleaned_data.get('units')
    if not units:
      raise forms.ValidationError('This field is required')
    return units

  def clean_item_name(self):
    item_name = self.cleaned_data.get('item_name')
    if not item_name:
      raise forms.ValidationError('This field is required')

    stocks = Stock.objects.all()
    for instance in stocks:
      if instance.item_name == item_name:
        raise forms.ValidationError(item_name + " exists")
    return item_name

  def clean_manufacturer(self):
    manufacturer = self.cleaned_data.get('manufacturer')
    if not manufacturer:
      raise forms.ValidationError('This field is required')
    return manufacturer


class StockSearchForm(forms.ModelForm):
  export_to_CSV = forms.BooleanField(required=False)
  class Meta:
    model = Stock
    fields = ['item_name', 'category', ]


class StockUpdateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subcategory'].widget.attrs['disable'] = True

    class Meta:
        model = Stock
        fields = ['category', 'subcategory', 'part_no', 'item_no',
        'item_name', 'manufacturer', 'quantity','units', 'rate' ]


    def clean_category(self):
      category = self.cleaned_data.get('category')
      if not category:
        raise forms.ValidationError('This field is required')
      return category

    def clean_sub_category(self):
      subcategory = self.cleaned_data.get('subcategory')
      if not subcategory:
        raise forms.ValidationError('This field is required')
      return subcategory

    def clean_part_no(self):
      part_no = self.cleaned_data.get('part_no')
      if not part_no:
        raise forms.ValidationError('This field is required')
      return part_no

    def clean_item_no(self):
      item_no = self.cleaned_data.get('item_no')

      return item_no

    # def clean_HSN_code(self):
    #   HSN_code = self.cleaned_data.get('HSN_code')
    #   if not HSN_code:
    #     raise forms.ValidationError('This field is required')
    #   return HSN_code

    def clean_units(self):
      units = self.cleaned_data.get('units')
      if not units:
        raise forms.ValidationError('This field is required')
      return units

    def clean_item_name(self):
      item_name = self.cleaned_data.get('item_name')
      if not item_name:
        raise forms.ValidationError('This field is required')
      return item_name

    def clean_manufacturer(self):
      manufacturer = self.cleaned_data.get('manufacturer')
      if not manufacturer:
        raise forms.ValidationError('This field is required')
      return manufacturer


class IssueForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['issue_quantity', 'issue_to']


class ReceiveForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['receive_quantity']

class IssueCreateForm(forms.ModelForm):
    class Meta:
        model = Issues
        fields = ['issue_quantity',  'issue_to']

    def clean_issue_quantity(self):
        issue_quantity = self.cleaned_data.get('issue_quantity')
        if not issue_quantity:
            raise forms.ValidationError('This field is required')
        return issue_quantity

    def clean_issue_to(self):
        issue_to = self.cleaned_data.get('issue_to')
        if not issue_to:
            raise forms.ValidationError('This field is required')
        return issue_to

stocks/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Stock, Issues
from .forms import *
from stocks.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import csv
from django.db.models import Sum, F, FloatField
# returns {'field_name__sum': 1000} for example

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'stocks/login.html', {})


def home(request):
    title = 'Home'
    context = {
    "header": title,
    }
    if request.user.is_authenticated:
        return render(request, "stocks/home.html",context)
    else:
        # render(request, "stocks/home.html",context)
        return render(request, "stocks/login.html",context)



@login_required
def list_items(request):
    title = 'List of Assets and Consumables'
    form = StockSearchForm(request.POST or None)
    queryset = Stock.objects.all()
    total = ( Stock.objects
                .aggregate(total=Sum(F('rate') * F('quantity'), output_field=FloatField()))['total']
         )
    context = {
        "header": title,
        "queryset": queryset,
        "total":total,
        "form": form,
    }
    if request.method == 'POST':
        queryset = Stock.objects.filter(
        item_name__icontains=form['item_name'].value(),
            category__icontains=form['category'].value(),
        )
        total = queryset.aggregate(total=Sum(F('rate') * F('quantity'),output_field=FloatField()))['total']

        if form['export_to_CSV'].value() == True:
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="List of stock.csv"'
            writer = csv.writer(response)
            writer.writerow(['CATEGORY','SUB CATEGORY','PART NO',
             'ITEM NO','ITEM NAME', 'QUANTITY', 'UNITS','RATE', 'VALUE'])
            instance = queryset
            for stock in instance:
                writer.writerow([stock.category,stock.subcategory,stock.part_no,
                stock.item_no,stock.item_name, stock.quantity, stock.units,
                stock.rate, (stock.quantity * stock.rate)])
            return response

        context = {
        "form": form,
        "header": title,
        "total": total,
        "queryset": queryset,
    }
    return render(request, "stocks/list_items.html", context)

@login_required
def add_items(request):
    form = StockCreateForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.updated_by = request.user.username
        instance.save()

        messages.success(request, 'Successfully Saved')
        return redirect('add_items')
    context = {
		"form": form,
		"header": "Add Assets or Consumables",
	}
    return render(request, "stocks/add_items.html", context)

@login_required
def update_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = StockUpdateForm(instance=queryset)
	if request.method == 'POST':
		form = StockUpdateForm(request.POST, instance=queryset)
		if form.is_valid():
			form.save()
			messages.success(request, 'Successfully Saved')
			return redirect('list_items')

	context = {
		'form':form,
        "header": "Update Assets or Consumables",
	}
	return render(request, 'stocks/update_items.html', context)

@login_required
def delete_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	if request.method == 'POST':
		queryset.delete()
		messages.success(request, 'Successfully Deleted')
		return redirect('list_items')
	return render(request, 'stocks/delete_items.html')

@login_required
def stock_detail(request, pk):
	queryset = Stock.objects.get(id=pk)
	context = {
		"queryset": queryset,
	}
	return render(request, "stocks/stock_detail.html", context)

@login_required
def issue_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = IssueForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity -= instance.issue_quantity
		# instance.issue_by = str(request.user)
		messages.success(request, "Issued SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name) + "s now left in Store")
		instance.save()

		return redirect('/stock_detail/'+str(instance.id))
		# return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": 'Issue ' + str(queryset.item_name),
		"queryset": queryset,
		"form": form,
	    "username": 'Issue By: ' + str(request.user),
	}
	return render(request, "stocks/add_items.html", context)

@login_required
def receive_items(request, pk):
	queryset = Stock.objects.get(id=pk)
	form = ReceiveForm(request.POST or None, instance=queryset)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.quantity += instance.receive_quantity
		instance.save()
		messages.success(request, "Received SUCCESSFULLY. " + str(instance.quantity) + " " + str(instance.item_name)+"s now in Store")

		return redirect('/stock_detail/'+str(instance.id))
		# return HttpResponseRedirect(instance.get_absolute_url())
	context = {
			"title": 'Receive ' + str(queryset.item_name),
			"instance": queryset,
			"form": form,
			"username": 'Receive By: ' + str(request.user),
		}
	return render(request, "stocks/add_items.html", context)

@login_required
def issue_items2(request, pk):
    a  = Stock.objects.get(id=pk)
    if request.method == 'POST':
        f = IssueCreateForm(request.POST)
        if f.is_valid():
            instance = f.save(commit=False)
            instance.updated_by = request.user.username
            if a.quantity >= instance.issue_quantity:
                a.quantity -= instance.issue_quantity
                a.save()
                instance.stock = a
                messages.success(request, "Issued SUCCESSFULLY. " + str(a.quantity) + " " + str(a.item_name) + "s now left in Store")
                instance.save()
            else:
                messages.error(request, "Issued failed. " + str(a.quantity) + " " + str(a.item_name) + "s is not enough to complete the issue")

            return redirect('/stock_detail/'+str(a.id))
    f = IssueCreateForm(request.POST)
    context={
		"title": 'Issue ' + str(a.item_name),
		"queryset": a,
		"form": f,
	    "username": 'Issue By: ' + str(request.user),
	}
    return render(request, "stocks/add_items.html", context)

stocks/templates/stocks/add_items.html
{% extends 'main/base_0.html' %}
<!--Block content goes below-->
{% load crispy_forms_tags %}
{% load static %}


{% block content %}
<link href="{% static 'css/add_item_master.css'  %}" rel="stylesheet" type="text/css">
      <div class="header">
          {{header}}
      </div>
      <form method='POST' action=''>{% csrf_token %}
        {{form|crispy}}
        <input type="submit" value='Save'/>
      </form>

  {% endblock content %}

stocks/templates/stocks/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
</head>
  <body>
    {% include 'navbar.html' %}
    <nav class="navbar navbar-default navbar-static-top">

      <div class="container">

        <ul class="nav navbar-nav">
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'stocks:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

stocks/templates/stocks/base_old.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->



  {% include 'navbar.html' %}

  {% block content %}
  {% endblock %}

stocks/templates/stocks/delete_items.html
{% extends 'main/base_0.html' %}

<!--Block content goes below-->

{% block content %}
{% include 'navbar.html' %}
  <main role="main" class="container">
    {% if messages %}
          <ul class="messages">
                 {% for message in messages %}
                       <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                 {% endfor %}
         </ul>
    {% endif %}
    <div class="jumbotron">
      <h1>{{header}}</h1>

      <form method="post" action="">
        {% csrf_token %}
          <h1>Are you sure you want to delete?</h1><br>
          <input class="btn btn-danger" type="submit" value="Yes" />
          <a href="/list_items"><div class="btn btn-primary">Cancel</div></a>
     </form>

    </div>
  </main>


  {% endblock %}

stocks/templates/stocks/home.html
{% extends 'main/base_0.html' %}
{% load static %}

<!--Block content goes below-->


  {% block content %}
  <style>
    .jumbotron{
      padding:0px;
    }
  </style>
    <img src="{% static 'img/with_children.jpg' %}" width='100%' alt="Landing Page">
  {% endblock %}

stocks/templates/stocks/index.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->


  {% block content %}
  <img src="{% static 'img/ais-stores2.jpg'  %}" alt="Landing Page">
  {% endblock %}

stocks/templates/stocks/list_items.html
{% extends 'main/base_0.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load humanize %}

<!--Block content goes below-->

{% block extra_head %}
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
{% endblock extra_head %}


{% block content %}

<main role="main" class="container-fluid">
  {% if messages %}
        <ul class="messages">
               {% for message in messages %}
                     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
               {% endfor %}
       </ul>
  {% endif %}
    <!-- <div class="jumbotron"> -->
        <div class="header">
          {{header}}
        </div>
        <span class="total_value">Value of Stock:{{total | floatformat:"0" | intcomma}}</span>
        <form method='POST' action=''>{% csrf_token %}
            {{form|crispy}}
                <input type="submit" value='Search'/>
        </form>

        <br>
      <div class="display_table">
        <table class='table'>
            <thead>
            <tr>
                <th>SR.NO</th>
                <th>CATEGORY</th>
                <th>SUB CAT.</th>
                <th>PART NO</th>
                <th>ITEM NAME</th>
                <th>STOCK</th>
                <th>UNITS</th>
                <th>RATE</th>
                <th>TIMESTAMP</th>
                <th>LAST UPDATED</th>
                <th>REORDER LEVEL</th>
            </tr>
            </thead>
            {% for instance in queryset %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{instance.category}}</td>
                    <td>{{instance.subcategory}}</td>
                    <td>{{instance.part_no}}</td>
                    <td><a href="{% url 'update_items' instance.id %}">{{instance.item_name}}</a></td>
                    <td><a href="{% url 'stock_detail' instance.id %}">{{instance.quantity}}</a></td>
                    <td>{{instance.units}}</td>
                    <td>{{instance.rate | intcomma }} </td>
                    <td>{{instance.timestamp}}</td>
                    <td>{{instance.last_updated}}</td>
                    <td>{{instance.reorder_level}}</td>
                </tr>

            {% endfor %}
        </table>
    </div>

    <!-- </div> -->
  </main>



{% endblock %}

stocks/templates/stocks/login.html
{% extends 'main/base_login.html' %}
{% load static %}
{% block navbar %}
{% endblock navbar %}
{% block login %}
      	<div class="d-flex justify-content-center h-100">
      		<div class="card">
      			<div class="card-header">
      				<h3>AIS Sign In</h3>
              <div class="logo_icon">
                <span><img src="{% static 'img/logo-sq2.png' %}"></span>
              </div>

              <!-- <div class="d-flex justify-content-end social_icon">
      					<span><i class="fab fa-facebook-square"></i></span>
      					<span><i class="fab fa-google-plus-square"></i></span>
      					<span><i class="fab fa-twitter-square"></i></span>
      				</div> -->
      			</div>
      			<div class="card-body">
              <form method="post" action="{% url 'stocks:user_login' %}" >
              {% csrf_token %}
      					<div class="input-group form-group">
      						<div class="input-group-prepend">
      							<span class="input-group-text"><i class="fas fa-user"></i></span>
      						</div>
      						<input type="text" class="form-control" name="username" placeholder="username">

      					</div>
      					<div class="input-group form-group">
      						<div class="input-group-prepend">
      							<span class="input-group-text"><i class="fas fa-key"></i></span>
      						</div>
      						<input type="password" class="form-control" name="password"  placeholder="password">
      					</div>
      					<!-- <div class="row align-items-center remember">
      						<input type="checkbox">Remember Me
      					</div> -->
      					<div class="form-group">
      						<input type="submit" value="Login" class="btn float-right login_btn">
      					</div>
      				</form>
      			</div>
      			<div class="card-footer">
      				<!-- <div class="d-flex justify-content-center links">
      					Don't have an account?<a href="#">Sign Up</a>
      				</div>
      				<div class="d-flex justify-content-center">
      					<a href="#">Forgot your password?</a>
      				</div> -->
      			</div>
      		</div>
      	</div>

{% endblock login %}

{% block content %}

{% endblock content %}

stocks/templates/stocks/register.html
{% extends 'main/base_0.html' %}
{% load static %}
<!--Block content goes below-->


<div class="container">
{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form }}
  </form>
  if you already have an account <a href="/login">login</a> instead.
{% endblock %}
</div>

stocks/templates/stocks/stock_detail.html
{% extends 'main/base_0.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<!--Block content goes below-->

{% block extra_head %}
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
{% endblock%}
{% block content %}

{% include 'navbar.html' %}
<main role="main" class="container">
    <div class="jumbotron">
      <div class="header">
          {{header}}
        </div>

        <br>
        <a href="{% url 'issue_items2' queryset.id %}"><div class='btn btn-danger'>ISSUE THIS ITEM</div></a>
        <a href="{% url 'receive_items' queryset.id %}"><div class='btn btn-primary'>RECEIVE THIS ITEM</div></a>

          <br><br>
          <div class="display_table">
            <table class='table'>
                    <tr>
                      <th>ITEM NAME</th>
                      <th>QUANTITY IN STORE</th>
                      <th>LAST UPDATED</th>
                      <th>REORDER LEVEL</th>
                    </tr>
                    <tr>
                      <td>{{queryset.item_name}}</td>
                      <td>{{queryset.quantity}}</td>
                      <td>{{queryset.last_updated}}</td>
                      <td>{{queryset.reorder_level}}</td>
                    </tr>
            </table>
          </div>

    </div>
  </main>
{% endblock %}

stocks/templates/stocks/update_items.html
{% extends 'main/base_0.html' %}
<!--Block content goes below-->
{% load crispy_forms_tags %}
{% load static %}


{% block content %}
<link href="{% static 'css/update_item_master.css'  %}" rel="stylesheet" type="text/css">
      <div class="header">
          {{header}}
      </div>
      <form method='POST' action=''>{% csrf_token %}
        {{form|crispy}}
        <input type="submit" value='Save'/>
      </form>

  {% endblock content %}